server:
  port: 8080
  servlet-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://120.25.124.62:3306/website
    username: ENC(upGWWGXygLsrKsDsXXTBAA==)
    password: ENC(yGOp+kZB+3x5G4X+CPKu+dNreobyRVWq6L/rHnW6EiA=)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    ### 数据源的其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    ### 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  #  redis:
  #    # Redis服务器地址
  #    host: localhost
  #    # Redis服务器连接密码（默认为空）
  #    password:
  #    # Redis服务器连接端口
  #    port: 6379
  #    # Redis数据库索引（默认为0）
  #    database: 0
  #    # 连接超时时间（毫秒）
  #    timeout: 5000
  #    # 连接池最大连接数（使用负值表示没有限制）
  #    pool:
  #      max-active: 8
  #      # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #      max-wait: -1
  #      # 连接池中的最大空闲连接
  #      max-idle: 8
  #      # 连接池中的最小空闲连接
  #      min-idle: 0

  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8

mybatis:
  mapper-locations: classpath*:mapper/xml/*.xml
  type-aliases-package: com.wchm.website.entity
  config-location:



# 配置jasypt安全框架加解密用的“盐”
jasypt:
  encryptor:
    password: G0CvDz7oJn6

# pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: rue
  params=count: countSql


wchm:
  # 服务器文件相对路径
  update-relative: /upload/
  # 服务器文件绝对路径
  update-absolutely: D:/upload/
  # 上传图片相对路径
  update-image-relative: /upload/images/
  # 上传图片绝对路径
  update-image-absolutely: D:/upload/images/
  # 白皮书文件地址
  paper-absolutely: D:/upload/paper/
  # 公司钱包地址 测试地址
  company-address: "0x9dC45C9BaE4D45aD8B45F492BbC51D7834EF170C"
  # 公司账户私钥 测试私钥
  company-pri-key: ""
  # PCT代币地址
  contract-address: "0x183630c3AfA08957E588eaa26b748cc5C2D42DC6"
  # 转账 method-id
  method-id: "0xa9059cbb000000000000000000000000"
  # 第三方请求以太坊接口数据访问地址
  infura-api: "https://mainnet.infura.io/v3/c783bc77104c4b2d8d7cca07e85dcbc5"
  # 查询钱包地址交易记录api地址
  address-transactions-url: "https://api.etherscan.io/api?module=account&action=tokentx&contractaddress=${wchm.contract-address}&startblock=0&endblock=99999999&page=[pageNum]&offset=[pageSize]&sort=desc&address=[address]&apikey=RAUWFA7NCA5H2IMDJ4V5GYK6ARVTA7Y23U"
  # keystore文件存放地址
  keystore-address: "F://keystore/pct/UTC--2018-11-06T01-21-53.686Z--252a5761cbe1e0711eec88ad90d333fa5e1fb2f6"
  # keystore文件密码
  keystore-password: "123456789"
  php:
    # php 解析token api
    token-api: "https://test-discuz.parkeco.io/api/v1/sign"
